name: CD - Relase

on:
  push:
    branches:
      - 'release/v*'
    paths:
        - "app/**"
        - "design-system/**"
        - ".github/workflows/cd-release.yml"
  pull_request:
    branches:
      - 'release/v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO Building
        run: echo building...