name: CD - Relase

on:
  [push, pull_request]:
    branches:
      - 'release/v*'
    paths:
        - "app/**"
        - "design-system/**"
        - ".github/workflows/cd-release.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO Building
        run: echo building...