name: CD - Relase

on:
  push:
    branches:
      - 'release/v*'
    paths:
      - "app/**"
      - "design-system/**"
      - ".github/workflows/cd-release.yml"
  push:
    types: [created]
    branches:
      - 'release/v*'
    
  # pull_request:
  #   types: [opened]
  #   branches:
  #     - 'main'
  #     - '!hotfix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO Building
        run: echo building...