name: CD - Relase

on:
  push:
    - 'release/v*'
  paths:
      - "app/**"
      - "design-system/**"
      - ".github/workflows/cd-release.yml"

jobs:
  build:
    runs-on: ubuntu-latest
      - name: ECHO Building
        run: echo building...