name: CD - Relase

on:
  push:
    branches:
      - 'release/v*'
    paths:
      - "app/**"
      - "design-system/**"
      - ".github/workflows/cd-release.yml"
  pull_request:
    types: [opened]
    branches:
      - 'main'
    branches-ignore:
      - 'hotfix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO Building
        run: echo building...