name: CD - Relase

on:
  pull_request:
    branches:
      - 'release/v*'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO Building
        run: echo building...