name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      releaseName:
          description: 'Nome da Release'
          required: true
          default: 'v2.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Check Branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo "A release deve ser gerada a partir da main"
          exit 1
      - name: Create Release Tag
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.releaseName }}
          token: ${{ github.token }}