name: Push do App em Staging

on:
  push:
    branches:
      - 'release/v*'
    paths:
      - "app/**"
      - ".github/workflows/push-app-release.yml"

jobs:
  publish-release-app:
    uses: ./.github/workflows/publica-app-staging.yml