name: Push da API em Staging

on:
  push:
    branches:
      - 'release/v*'
    paths:
      - "api/**"
      - ".github/workflows/release-push-api.yml"

jobs:
  publish-release-api:
    uses: ./.github/workflows/publish-release-api.yml
