name: Push da API em Staging

on:
  push:
    branches:
      - 'release/v*'
    paths:
      - "api/**"
      - ".github/workflows/push-api-release.yml"

jobs:
  publish-release-api:
    uses: ./.github/workflows/publica-api-staging.yml
