name: Push do App em Staging

on:
  push:
    branches:
      - 'release/v*'
    paths:
      - "app/**"
      - ".github/workflows/release-push-app.yml"

jobs:
  publish-release-app:
    uses: ./.github/workflows/publish-release-app.yml